
version: 2

models:
  - name: dim_customer
    description: "dim_customer"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


