dbtetl:
  outputs:
    dev:
      dataset: retail_dsy
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      keyfile: /secrets/dbt-keyfile
      priority: interactive
      project: retail-etl
      threads: 1
      type: bigquery
  target: dev
